Visitenkarte: |md
  # Visitenkarte
  Interesse an lokalen Bio-Produkten?
|

Registrierung: |md
  # Registrierung
  [ ] check query parameters for QR code origin
  
  
  Bleiben Sie auf dem neusten Stand und erhalten Sie Zugang zu unseren aktuellen [Bio-Produkten]!
  
  ---
  
  - Name
  - E-Mail
  - Passwort
  
  ---
  
  -> Registrieren
|

Produkte-Seite: |md
  # Produkte-Seite
|

Visitenkarte -> Registrierung: QR-Code
Registrierung -> Produkte-Seite: verlinkt
