export const db = "main-permdal"
export const orderCollection = "orders"
export const postCollection = "posts"
export const eventCollection = "events"
export const productsCollection = "produkte"
export const staffelCollection = "677d223d000492d2e618"
